AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket to store Athena queries

Parameters:
  pBucketName:
        Type: String
        Description: s3 destination bucket

Resources:
  Type: AWS::S3::Bucket
  Properties: 
    BucketName: !Ref pBucketName
